paths:
  /ask/mail:
    post:
      tags:
        - ask
      summary: 문의하기
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                  default: '발송 메일의 제목을 입력해주세요'
                text:
                  type: string
                  default: '발송 메일의 내용을 입력해주세요'
                email:
                  type: string
                  default: '회신을 위한 이메일 주소를 입력해주세요 / 미입력시 회신 원치 않음'
      security:
        - bearerAuth: []
      responses:
        '201':
          description: success
        '400':
          description: 잘못된 요청
        '401':
          description: 로그인 정보 없음
        '500':
          description: 메일 발송 서버 오류