# paths:
#   /ask:
#     get:
#       tags:
#         - ask
#       summary: 모든 문의 조회
#       responses:
#         '200':
#           description: 모든 문의 출력
#         '500':
#           description: ERROR
#     post:
#       tags:
#         - ask
#       summary: 제보 생성 - Authorization 키 필요
#       parameters:
#         - in: body
#           name: ask_title
#           required: true
#           schema:
#             type: string
#         - in: body
#           name: ask_contents
#           required: true
#           schema:
#             type: string
#       responses:
#         '200':
#           description: 생성된 제보 출력
#         '500':
#           description: ERROR

#   /ask/me:
#     get:
#       tags:
#         - ask
#       summary: 내가 한 문의 조회 - Authorization 키 필요
#       responses:
#         '200':
#           description: 내 전체 문의 출력
#         '500':
#           description: ERROR

#   /ask/me/{askId}:
#     delete:
#       tags:
#         - ask
#       summary: 내가 한 특정 문의 삭제 - Authorization 키 필요
#       parameters:
#         - in: params
#           name: askId
#           required: true
#           schema:
#             type: string
#       responses:
#         '200':
#           description: 삭제된 문의 출력
#         '500':
#           description: ERROR

#   /ask/user/{userId}:
#     get:
#       tags:
#         - ask
#       summary: 특정 유저 문의 조회
#       parameters:
#         - in: params
#           name: userId
#           required: true
#           schema:
#             type: string
#       responses:
#         '200':
#           description: 특정 유저 문의 출력
#         '500':
#           description: ERROR
