paths:
  /post:
    post:
      tags:
        - post
      summary: 제보 작성 - Authorization 키 필요
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                store:
                  type: string
                storeName:
                  type: string
                kakaoId:
                  type: string
                addressX:
                  type: number
                addressY:
                  type: number
                drink:
                  type: string
                comment:
                  type: string
            examples:
              store does not exists:
                summary: store does not exists
                value:
                  storeName: BHC 상암동
                  kakaoId: 123456
                  addressX: 123.456
                  addressY: 123.456
                  drink: 코카콜라
                  comment: 코카콜라가 왔어요 !
              store alreay exists:
                summary: store alreay exists
                value:
                  store: 123456
                  drink: 코카콜라
                  comment: 코카콜라가 왔어요 !
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK

  /post/store/{storeId}:
    get:
      tags:
        - post
      summary: 특정 스토어의 제보 조회
      parameters:
        - in: path
          name: storeId
          required: true
          schema:
            type: string
            default: '123456'
      responses:
        '200':
          description: OK

  /post/user:
    get:
      tags:
        - post
      summary: 내가 한 제보 조회 - Authorization 키 필요
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK

  /post/{postId}:
    delete:
      tags:
        - post
      summary: 내가 한 제보 삭제 - Authorization 키 필요
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
