paths:
  /user:
    get:
      tags:
        - user
      summary: 모든 유저 조회(임시)
      responses:
        '200':
          description: 모든 유저 목록 출력
        '400':
          description: ERROR

  /user/profile:
    get:
      tags:
        - user
      summary: 유저 프로필 페이지
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 유저 정보 출력
        '400':
          description: ERROR

  /user/nickname:
    patch:
      tags:
        - user
      summary: 닉네임 변경
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                profileNickname:
                  type: string
                  default: '바보'
      security:
        - bearerAuth: []
      responses:
        '201':
          description: 유저의 닉네임을 변경하고 변경된 닉네임 출력
        '400':
          description: ERROR

  /user/quit:
    delete:
      tags:
        - user
      summary: 회원 탈퇴
      security:
        - bearerAuth: []
      responses:
        '204':
          description: 삭제 처리된 유저 출력
        '400':
          description: ERROR