paths:
  /user:
    get:
      tags:
        - user
      summary: GET ALL OF USER
      responses:
        '200':
          description: OK

  /user/{userId}:
    delete:
      tags:
        - user
      summary: DELETE ONE USER
      responses:
        '200':
          description: OK

  /user/login:
    post:
      tags:
        - user
      summary: LOGIN
      parameters:
        - in: query
          name: uniqId
          required: true
          schema:
            type: string
            default: '123457'
      responses:
        '200':
          description: OK
