paths:
  /user/login:
    post:
      tags:
      - user
      summary: LOGIN
      parameters: 
        - in: query
          name: uniqId
          required: true
          schema: 
            type: string
            default: '123457' 
      responses:
        '200':
          description: OK